spring.application.name=backend

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=THIS_IS_MY_SUPER_SECRET_KEY_FOR_JWT_AUTHENTICATION_2026

cloudinary.cloud-name=dv0of5por
cloudinary.api-key=366318783969996
cloudinary.api-secret=a0uo6SPBOMUL9SHuUxoAouDZEeg